import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Khushkuro
 */

public class SignUp_Frame extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_Frame
     */
    public SignUp_Frame() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_registor = new javax.swing.JButton();
        text_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_confirn_password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        text_loginFrame = new javax.swing.JLabel();
        text_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registor.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_registor.setText("Register");
        btn_registor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 130, 40));

        text_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 210, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 210, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MC Invertory Managment System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        text_confirn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_confirn_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(text_confirn_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 230, 40));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });
        getContentPane().add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 230, 40));

        text_loginFrame.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        text_loginFrame.setForeground(new java.awt.Color(255, 255, 255));
        text_loginFrame.setText("Back to Login");
        text_loginFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_loginFrameMouseClicked(evt);
            }
        });
        getContentPane().add(text_loginFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 120, -1));

        text_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Neon Background 2.jpg"))); // NOI18N
        getContentPane().add(text_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registorActionPerformed
        String username = text_username.getText();
        String password = text_password.getText();

        if(text_username.getText().trim().isEmpty() || text_email.getText().trim().isEmpty() || text_password.getText().trim().isEmpty() || text_confirn_password.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "FIll The All Fields");
        }
        
        else{
            try{
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mc_ims_db", "root", "1234");

                Statement statement = connection.createStatement();

                ResultSet rs = statement.executeQuery("SELECT MAX(serial_no) FROM login_table");
                int maxSerial = 0;
                        
                if (rs.next()) {
                    maxSerial = rs.getInt(1);
                }
                
                rs.close();
                statement.close();

                PreparedStatement pstmt = connection.prepareStatement("INSERT INTO login_table(serial_no, username, password) VALUES (?, ?, ?)");
                pstmt.setInt(1, maxSerial + 1);
                pstmt.setString(2, username);
                pstmt.setString(3, password);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Added");

                text_username.setText("");
                text_email.setText("");
                text_password.setText("");
                text_confirn_password.setText("");

                connection.close();
            }

            catch(Exception mubeen){
                System.out.println(mubeen);
            }
        }   
    }//GEN-LAST:event_btn_registorActionPerformed

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void text_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passwordActionPerformed

    private void text_confirn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_confirn_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_confirn_passwordActionPerformed

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_emailActionPerformed

    private void text_loginFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_loginFrameMouseClicked
        new Login_Frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_text_loginFrameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField text_confirn_password;
    private javax.swing.JTextField text_email;
    private javax.swing.JLabel text_image;
    private javax.swing.JLabel text_loginFrame;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
